<?php
namespace  app\index\model;
use think\Model;
use think\Db;
class  Admin extends Model{
  protected  function  initialize()
  {
      parent::initialize(); // TODO: Change the autogenerated stub
      echo "chushihau1";
  }

//    public function Logincontroller($data){
//        $user=Db::name('admin')->where('username','=',$data['username'])->find();
//        if($user){
//            if($user['password'] == md5($data['password'])){
//                session('username',$user['username']);
//                session('uid',$user['id']);
//                return 3; //信息正确
//            }else{
//                return 2;//密码错误
//            }
//        }else{
//            return 1;//用户不存在
//        }
//    }

}
?>